Vaelthor = ["Alaric", "Elora", "Kaelen", "Thalia", "Bram", "Sestia", "Darius", "Lyra", "Gideon", "Mirella", "Silas", "Rowena", "Caspian", "Aria", "Thorne", "Isolde", "Kaelic", "Selene", "Varin", "Elowen", "Malachi", "Freyja", "Osric", "Liora", "Caelum", "Vespera", "Tobias", "Seraphina", "Jaxon", "Katarina", "Elias", "Amara", "Finnian", "Valerius", "Nyx", "Gareth", "Elara", "Dante", "Sienna", "Zephyr", "Maeve", "Cillian", "Odessa", "Alistair", "Eveline", "Ronan", "Blythe", "Kellan", "Thais", "Cyrus", "Lumi", "Kael", "Sariel", "Eamon", "Vindra", "Kester", "Amaris", "Torin", "Lysandra", "Roric", "Fenna", "Aris", "Calista", "Lucian", "Talia", "Stellan", "Zora", "Koa", "Mira", "Hadrian", "Aislin", "Quill", "Sora", "Doran", "Evadne", "Belaric", "Nyssa", "Talon", "Ione", "Kaelthas", "Lark", "Vane", "Estel", "Zander", "Aethel", "Rhea", "Kovash", "Indra", "Tavish", "Sola", "Corvin", "Aislynn", "Bael", "Karys", "Merrick", "Lyana", "Torren", "Vael", "Syrrus", "Lianna"]

Drovenar = ["Brakkas", "Durnin", "Grogna", "Thrain", "Korgul", "Dain", "Bofur", "Gimli", "Hogar", "Thror", "Beldrum", "Kili", "Durin", "Gloin", "Farin", "Borin", "Gromm", "Thargrim", "Orik", "Dwalin", "Thorin", "Balin", "Nori", "Dori", "Ori", "Grombur", "Taurin", "Thrain", "Fundin", "Gróin", "Throrin", "Bifur", "Bombur", "Moriah", "Gundar", "Thokk", "Rurik", "Haldor", "Ulfgar", "Kildrak", "Eberk", "Adrik", "Baern", "Brottor", "Duerg", "Fargrim", "Gardain", "Harbek", "Logar", "Orsik", "Oskar", "Rangrim", "Thoradin", "Travok", "Vondal", "Groth", "Barak", "Dunrag", "Korgath", "Mordak", "Torgrim", "Vunnor", "Galdrik", "Balthar", "Ragnir", "Drakka", "Thronar", "Kromm", "Grum", "Torrig", "Brodar", "Hognar", "Dramin", "Gorth", "Kaldar", "Vorgun", "Thruon", "Gromma", "Derna", "Brylra", "Krysta", "Marga", "Grizel", "Thilda", "Dagny", "Helga", "Sifna", "Runa", "Gunnra", "Hilda", "Vistra", "Torra", "Mardra", "Garnet", "Ruby", "Dwarra", "Barda", "Olka", "Gretel", "Kala"]

Sylmari = ["Aeliana", "Thalanil", "Elowen", "Ivorwen", "Faelyn", "Sylvaris", "Luthien", "Aredhel", "Valerius", "Galadriel", "Caelum", "Erendriel", "Haldir", "Legolas", "Thranduil", "Celeborn", "Arwen", "Elrond", "Gil-galad", "Maedhros", "Fingolfin", "Finrod", "Ecthelion", "Glorfindel", "Erestor", "Cirdan", "Lariel", "Nimue", "Tauriel", "Feren", "Lindir", "Elladan", "Elrohir", "Aegnor", "Amras", "Amrod", "Curufin", "Celegorm", "Caranthir", "Maglor", "Voronwë", "Idril", "Turgon", "Aulendil", "Valyra", "Zylra", "Lysanthir", "Eryn", "Mithrellas", "Finduilas", "Nellas", "Elwing", "Eärendil", "Olwen", "Denethor", "Lenwë", "Beleg", "Mablung", "Saeros", "Gwindor", "Oropher", "Amroth", "Galathil", "Celebrian", "Aranhir", "Vaelen", "Sariel", "Kaelen", "Fëanor", "Nerdanel", "Anairë", "Eärwen", "Indis", "Miriel", "Telerin", "Amarië", "Elenwë", "Silmariel", "Isilme", "Vardilmë", "Eldalótë", "Lindariel", "Evranel", "Thalindra", "Maelas", "Keyleth", "Vax'ildan", "Vex'ahlia", "Lathariel", "Orym", "Laerwen", "Fenris", "Zevlor", "Halsin", "Minthara", "Astarion", "Jaheira", "Viconia", "Irenicus", "Ellerian"]

Gorvash = ["Grommash", "Thokk", "Garad", "Mogra", "Korgalg", "Durotan", "Gul'dan", "Blackhand", "Orgrim", "Rexxar", "Nazgrel", "Kargath", "Broxigar", "Varok", "Drak'thul", "Grom", "Garrosh", "Eitrigg", "Mankrik", "Zul'jin", "Rokhan", "Gidwin", "Krazz", "Thrum", "Gortat", "Urog", "Borgul", "Grak", "Krum", "Zog", "Muzgok", "Rotgur", "Azog", "Bolg", "Lurtz", "Uglúk", "Grishnákh", "Mauhúr", "Shagrat", "Gorbag", "Snaga", "Lagduf", "Radbug", "Ufthak", "Muzg", "Gothmog", "Zul", "Throk", "Kurdan", "Ghak", "Vrog", "Kurg", "Drog", "Thrak", "Grol", "Mug", "Zug", "Kraz", "Throk", "Drak", "Gorn", "Zorn", "Korn", "Morn", "Thorn", "Gruk", "Zruk", "Kruk", "Mruk", "Thruk", "Gash", "Zash", "Kash", "Mash", "Thash", "Grok", "Zrok", "Krok", "Mrok", "Throk", "Grumm", "Zrumm", "Krumm", "Mrumm", "Thrumm", "Graka", "Mogga", "Korgi", "Zulga", "Thara", "Gora", "Brak", "Draka", "Geya", "Aggra", "Maka", "Raka", "Zaka", "Kaka", "Nara"]

Sharusahk = ["Zashek", "Shariel", "Khasir", "Sural", "Tashka", "Zeyl", "Muzira", "Khes", "Sharun", "Vesk", "Zulari", "Shaykh", "Khazal", "Sarith", "Tesh", "Zirah", "Shek", "Kharam", "Shunari", "Valkar", "Zeyth", "Shasul", "Khoris", "Suran", "Teylan", "Zos", "Shakira", "Khul", "Sarem", "Veyra", "Zashin", "Shuval", "Kheris", "Sith", "Taran", "Zulka", "Sharos", "Khir", "Sula", "Veskari", "Zeyan", "Shun", "Khasem", "Sarith", "Tishar", "Zoral", "Sheyn", "Kharul", "Sariel", "Vey", "Zush", "Shakal", "Khayra", "Sareth", "Talir", "Zin", "Shura", "Khet", "Sulin", "Vora", "Zeyka", "Sharis", "Khosan", "Suriel", "Tey", "Zarku", "Shon", "Kharez", "Sithan", "Valki", "Zeym", "Shas", "Khurak", "Sari", "Tash", "Zul", "Shekari", "Khesul", "Soram", "Veym", "Zira", "Shal", "Khari", "Suth", "Toren", "Zey", "Shuk", "Khen", "Sora", "Vul", "Zar", "Shay", "Khoz", "Sath", "Tuk", "Zosh", "Shiri", "Khar", "Sil", "Tosh"]
